### ISSUE TITLE
doesnt work on Firefox

### ISSUE THREAD

**Issue by ghost** [tan-z-tan/GitHubGuessr#1] opened 2023-09-09 04:10 UTC
~~~
TypeError: e is undefined
    NextJS 11
[framework-63157d71ad419e09.js:9:69810](https://github-guessr.vercel.app/_next/static/chunks/framework-63157d71ad419e09.js)
Uncaught TypeError: e is undefined
    NextJS 11
[main-c59a42b9e9a6f445.js:1:11213](https://github-guessr.vercel.app/_next/static/chunks/main-c59a42b9e9a6f445.js)
~~~

**Comment by zachtyll** [comment] 2023-09-09 07:43
Additional information: Tested it with Firefox for Android and it worked.

**Comment by tan-z-tan** [comment] 2023-09-09 12:16
Thank you for the feedback!
May I ask for more details about your environment? I read your comment and tried it on both Firefox for Mac and Firefox for Android, but I didn't see any errors.

**Comment by 1268** [comment] 2023-09-09 12:45
what details

**Comment by Arizona-dev** [comment] 2023-09-13 13:03
Found this issue on NextJS repo, it doesn't work on version 101 of Firefox.

**Comment by Arizona-dev** [comment] 2023-09-13 13:20
Did some digging, and it is caused by next.js using performanceMesure, which is only available from Firefox 103.

https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure

As it doesn't exists, the variables in next.js build, beforeHydrationMeasure and hydrationMeasure are undefined which causes the error to be thrown.

**Comment by Arizona-dev** [comment] 2023-09-13 15:23
The NextJS development team has made a fix for this issue, see [file](https://github.com/vercel/next.js/pull/54808/files).
It is available in canary release, so maybe next stable version of NextJS will include this fix.

**Comment by tan-z-tan** [comment] 2023-09-13 16:35
Indeed, I got an error when I ran it on the older version. Thank you for your help!

I'll fix it in this Pull Request https://github.com/tan-z-tan/GitHubGuessr/pull/5

**Closed as completed** 2023-09-13 16:37 UTC
